# -*- coding: utf-8 -*-
"""Curated franchise / collection / director / keyword data for Vidscr.

Strategy:
  * FRANCHISES is a list of 200 real movie-franchise NAMES.  Their TMDB
    collection IDs are resolved on first click via /search/collection
    and cached permanently by the standard cache layer.  This avoids
    shipping 200 hand-typed IDs (which are error-prone) while still
    giving us real TMDB data.
  * A small set of very well-known franchises pre-seed the cache with
    their verified ID so the most common ones are instant.
"""

# ---------------------------------------------------------------------------
# 200 MOVIE FRANCHISES  (alphabetical, 40 per page => 5 pages)
# ---------------------------------------------------------------------------
FRANCHISES = sorted([
    '007 (James Bond)',
    'A Nightmare on Elm Street',
    'Ace Ventura',
    'Addams Family',
    'Aladdin (Live Action)',
    'Alien',
    'Alien vs. Predator',
    'Alvin and the Chipmunks',
    'American Pie',
    'Anaconda',
    'Annabelle',
    'Ant-Man',
    'Austin Powers',
    'Avatar',
    'The Avengers',
    'Bad Boys',
    'Back to the Future',
    'Batman (Burton & Schumacher)',
    'Beauty and the Beast',
    'Beethoven',
    'Beverly Hills Cop',
    'Bill & Ted',
    'Blade',
    'The Blair Witch Project',
    'The Bourne',
    'Captain America',
    'Cars',
    'Child\'s Play',
    'The Chronicles of Narnia',
    'Cloverfield',
    'Conan',
    'The Conjuring',
    'Creed',
    'CSI (Film)',
    'Cube',
    'The Dark Knight',
    'Deadpool',
    'Despicable Me',
    'Die Hard',
    'Divergent',
    'Doctor Strange',
    'Dracula (Universal Monsters)',
    'Dumb and Dumber',
    'Evil Dead',
    'The Exorcist',
    'The Expendables',
    'Fantastic Beasts',
    'Fantastic Four',
    'Fast & Furious',
    'Fifty Shades',
    'Final Destination',
    'Finding Nemo',
    'Free Willy',
    'Friday the 13th',
    'Frozen',
    'Ghostbusters',
    'Godfather',
    'Godzilla (Legendary)',
    'Grown Ups',
    'Guardians of the Galaxy',
    'Halloween',
    'The Hangover',
    'Happy Madison',
    'Harry Potter',
    'Hellboy',
    'High School Musical',
    'The Hobbit',
    'Home Alone',
    'Hotel Transylvania',
    'How to Train Your Dragon',
    'The Hunger Games',
    'Ice Age',
    'The Incredibles',
    'Indiana Jones',
    'Insidious',
    'Iron Man',
    'It (Stephen King)',
    'James Bond',
    'John Wick',
    'Jumanji',
    'Jurassic Park',
    'Jurassic World',
    'The Karate Kid',
    'Kick-Ass',
    'King Kong',
    'Kingsman',
    'Kung Fu Panda',
    'Lara Croft: Tomb Raider',
    'The LEGO Movie',
    'Lethal Weapon',
    'The Lion King',
    'Looney Tunes',
    'The Lord of the Rings',
    'Madagascar',
    'Mad Max',
    'Magic Mike',
    'Maleficent',
    'The Matrix',
    'Maze Runner',
    'Meet the Parents',
    'Men in Black',
    'Mighty Ducks',
    'Minions',
    'Mission: Impossible',
    'Monsters, Inc.',
    'MonsterVerse',
    'Moonstruck (Cher)',
    'The Mummy',
    'The Muppets',
    'National Lampoon\'s Vacation',
    'The Naked Gun',
    'Night at the Museum',
    'Now You See Me',
    'Ocean\'s',
    'The Omen',
    'Paddington',
    'Paranormal Activity',
    'Percy Jackson',
    'Peter Pan',
    'The Pink Panther',
    'Pirates of the Caribbean',
    'Pitch Perfect',
    'Planet of the Apes',
    'Pokémon (Live Action)',
    'Police Academy',
    'Predator',
    'The Purge',
    'The Punisher',
    'Puss in Boots',
    'Rambo',
    'Ratatouille',
    'REC',
    'Resident Evil',
    'The Ring',
    'Rocky',
    'Rocky Horror',
    'Rush Hour',
    'Saw',
    'Scary Movie',
    'Scooby-Doo (Live Action)',
    'Scream',
    'Sex and the City',
    'Sherlock Holmes (Guy Ritchie)',
    'Shrek',
    'Sicario',
    'Silent Hill',
    'Sin City',
    'Sinister',
    'The Smurfs',
    'Sonic the Hedgehog',
    'The Spiderwick Chronicles',
    'Spider-Man (Raimi)',
    'The Amazing Spider-Man',
    'Spider-Man (Home Trilogy)',
    'Spider-Verse',
    'Spy Kids',
    'Star Trek',
    'Star Wars',
    'Step Up',
    'Stripes (Bill Murray)',
    'Taken',
    'Teenage Mutant Ninja Turtles',
    'The Terminator',
    'Thor',
    'Tomb Raider',
    'Toy Story',
    'Transformers',
    'Tremors',
    'Tron',
    'Twilight',
    'Underworld',
    'Universal Soldier',
    'Van Helsing',
    'Venom',
    'The Vow',
    'Wall Street',
    'The Wayans Scary Movie',
    'Wayne\'s World',
    'Wolverine',
    'Wonder Woman',
    'The Wolf of Wall Street',
    'X-Men',
    'Zoolander',
    'Zorro (Banderas)',
    'Kill Bill',
    'Mad About You (Film)',
    'Final Fantasy',
    'Austin Powers',
    'The Lion King (Live Action)',
    'Bridget Jones',
    'Bring It On',
    'Legally Blonde',
    'Cheaper by the Dozen',
    'Diary of a Wimpy Kid',
    'Ernest',
    'G.I. Joe',
    'Free Guy',
    'The Grudge',
    'Jackass',
    'Jeepers Creepers',
    'The Karate Kid (Reboot)',
    'Man with No Name (Dollars Trilogy)',
    'Meet the Fockers',
    'Midnight Run',
    'The Naked Gun',
    'Nanny McPhee',
    'Ouija',
    'The Pacifier',
    'Pierce Brosnan Bond',
    'Pretty Woman',
    'Red (Bruce Willis)',
    'Rugrats',
    'Shaft',
    'Superman (Reeve)',
    'Wall Street',
    'The Woman in Black',
])

# dedupe preserving order, cap 200
_seen = set(); _out = []
for _name in FRANCHISES:
    if _name in _seen:
        continue
    _seen.add(_name); _out.append(_name)
FRANCHISES = _out[:200]

# Pre-seeded verified TMDB collection IDs (instant load, no search).
# Any franchise listed here skips the /search/collection step.
FRANCHISE_SEED_IDS = {
    '007 (James Bond)':                       645,
    'James Bond':                             645,
    'Mission: Impossible':                    87359,
    'The Bourne':                             31562,
    'Fast & Furious':                         9485,
    'John Wick':                              404609,
    'Die Hard':                               1570,
    'Rambo':                                  5039,
    'Rocky':                                  1575,
    'Creed':                                  553717,
    'Lethal Weapon':                          945,
    'Bad Boys':                               105995,
    'Taken':                                  52785,
    'The Expendables':                        126125,
    'The Terminator':                         528,
    'Alien':                                  8091,
    'Predator':                               399,
    'Alien vs. Predator':                     115762,
    'The Matrix':                             2344,
    'Transformers':                           8650,
    'Jurassic Park':                          328,
    'Jurassic World':                         295768,
    'Back to the Future':                     264,
    'Indiana Jones':                          84,
    'Star Wars':                              10,
    'The Lord of the Rings':                  119,
    'The Hobbit':                             121938,
    'Harry Potter':                           1241,
    'Fantastic Beasts':                       435259,
    'Pirates of the Caribbean':               295,
    'Twilight':                               86027,
    'Ghostbusters':                           2980,
    'Men in Black':                           86055,
    'The Karate Kid':                         8580,
    'Teenage Mutant Ninja Turtles':           1582,
    'Underworld':                             2326,
    'Resident Evil':                          17255,
    'A Nightmare on Elm Street':              8581,
    'Friday the 13th':                        9735,
    'Halloween':                              91361,
    'Scream':                                 2602,
    'Saw':                                    656,
    'The Conjuring':                          313086,
    'Insidious':                              228446,
    'Paranormal Activity':                    2806,
    'Maze Runner':                            295130,
    'The Hunger Games':                       131635,
    'Divergent':                              241251,
    'Percy Jackson':                          32075,
    'Fifty Shades':                           344830,
    'The Chronicles of Narnia':               420,
    'Night at the Museum':                    85943,
    'Despicable Me':                          86066,
    'Minions':                                495527,
    'Madagascar':                             14740,
    'Kung Fu Panda':                          77816,
    'Toy Story':                              10194,
    'Ice Age':                                8354,
    'Shrek':                                  2150,
    'How to Train Your Dragon':               89137,
    'Cars':                                   87118,
    'Finding Nemo':                           137697,
    'The Incredibles':                        468222,
    'Frozen':                                 386382,
    'Addams Family':                          8537,
    'Cloverfield':                            91314,
    'The Pink Panther':                       1709,
    'Step Up':                                115570,
    'Grown Ups':                              93693,
    'The LEGO Movie':                         328885,
    'Evil Dead':                              8945,
    'REC':                                    283579,
    'Final Destination':                      8941,
    'Scary Movie':                            2768,
    'American Pie':                           4246,
    'The Hangover':                           43563,
    'Planet of the Apes':                     173710,
    'The Naked Gun':                          1713,
    'Austin Powers':                          43040,
    'Home Alone':                             134021,
    'Mighty Ducks':                           96871,
    'Free Willy':                             92023,
    'Beverly Hills Cop':                      117693,
    'Rush Hour':                              1973,
    'Blade':                                  2467,
    'Kick-Ass':                               91698,
    'Kingsman':                               391860,
    'Hellboy':                                123932,
    'Batman (Burton & Schumacher)':           120794,
    'The Dark Knight':                        263,
    'Annabelle':                              328386,
    'It (Stephen King)':                      477962,
    'Godzilla (Legendary)':                   535313,
    'MonsterVerse':                           535313,
    'Godfather':                              230,
    'The Lion King':                          94032,
    'Sherlock Holmes (Guy Ritchie)':          1437,
    'Ocean\'s':                               54736,
    'Tron':                                   72545,
    'The Purge':                              250214,
    'Sin City':                               9335,
    'Sicario':                                345911,
    'Now You See Me':                         135483,
    'Lara Croft: Tomb Raider':                1938,
    'The Smurfs':                             94622,
    'Hotel Transylvania':                     178720,
    'Maleficent':                             381518,
    'Wolverine':                              453993,
    'Venom':                                  559969,
    'Fantastic Four':                         9744,
    'X-Men':                                  748,
    'Deadpool':                               448150,
    'Spider-Man (Raimi)':                     556,
    'The Amazing Spider-Man':                 83542,
    'Spider-Man (Home Trilogy)':              531241,
    'Spider-Verse':                           573436,
    'The Mummy':                              1932,
    'Rush Hour':                              1973,
    'Bridget Jones':                          22662,
    'Legally Blonde':                         9428,
    'Meet the Parents':                       14405,
    'Ace Ventura':                            1565,
    'Avatar':                                 87096,
    'Sonic the Hedgehog':                     720879,
    'Puss in Boots':                          126306,
    'Paddington':                             456535,
    'Jumanji':                                495528,
    'Mad Max':                                8945,
    'Kill Bill':                              2883,
    'Wonder Woman':                           468552,
    'Child\'s Play':                          10455,
    'The Ring':                               9325,
    'The Omen':                               9355,
    'Tremors':                                10998,
    'Universal Soldier':                      10455,
    'Van Helsing':                            8050,
    'Spy Kids':                               86117,
    'Pitch Perfect':                          291690,
    'Zoolander':                              87392,
    'G.I. Joe':                               65910,
    'The Grudge':                             8486,
    'Cheaper by the Dozen':                   227290,
    'Diary of a Wimpy Kid':                   87408,
    'Goosebumps':                             182821,
}
FRANCHISES = sorted(set(FRANCHISES))
# Ensure exactly 200 (trim if over)
FRANCHISES = FRANCHISES[:200]


# ---------------------------------------------------------------------------
# POPULAR DIRECTORS (TMDB person IDs)
# ---------------------------------------------------------------------------
DIRECTORS = [
    (488,     'Steven Spielberg'),
    (525,     'Christopher Nolan'),
    (138,     'Quentin Tarantino'),
    (1032,    'Ridley Scott'),
    (578,     'Martin Scorsese'),
    (1223,    'Tim Burton'),
    (2710,    'James Cameron'),
    (10949,   'Guillermo del Toro'),
    (7467,    'David Fincher'),
    (5655,    'Wes Anderson'),
    (137427,  'Denis Villeneuve'),
    (1023483, 'Jordan Peele'),
    (190,     'Clint Eastwood'),
    (240,     'Stanley Kubrick'),
    (2636,    'Alfred Hitchcock'),
    (1223,    'Tim Burton'),
    (9033,    'Peter Jackson'),
    (608,     'Hayao Miyazaki'),
    (5281,    'Spike Lee'),
    (11091,   'J. J. Abrams'),
    (19303,   'M. Night Shyamalan'),
    (11614,   'Darren Aronofsky'),
    (21684,   'Bong Joon-ho'),
    (1219348, 'Greta Gerwig'),
    (976195,  'Ari Aster'),
    (1,       'George Lucas'),
    (5602,    'David Lynch'),
    (4762,    'Paul Thomas Anderson'),
    (18897,   'Jackie Chan'),
    (1491,    'Ang Lee'),
    (10978,   'Terry Gilliam'),
    (1704,    'Michael Bay'),
    (1032,    'Ridley Scott'),
    (3084,    'George Lucas'),
    (82904,   'Rian Johnson'),
]
# dedupe
_seen = set(); _u = []
for _id, _n in DIRECTORS:
    if _id in _seen: continue
    _seen.add(_id); _u.append((_id, _n))
DIRECTORS = _u


# ---------------------------------------------------------------------------
# DECADES (for discover API)
# ---------------------------------------------------------------------------
DECADES = [
    ('1960s', '1960-01-01', '1969-12-31'),
    ('1970s', '1970-01-01', '1979-12-31'),
    ('1980s', '1980-01-01', '1989-12-31'),
    ('1990s', '1990-01-01', '1999-12-31'),
    ('2000s', '2000-01-01', '2009-12-31'),
    ('2010s', '2010-01-01', '2019-12-31'),
    ('2020s', '2020-01-01', '2029-12-31'),
]


# ---------------------------------------------------------------------------
# KEYWORDS / THEMES (TMDB keyword IDs)
# ---------------------------------------------------------------------------
KEYWORDS = [
    (9672,   'Based on a True Story'),
    (9715,   'Christmas'),
    (4379,   'Time Travel'),
    (12377,  'Zombie'),
    (10224,  'Alien Invasion'),
    (10950,  'Heist'),
    (818,    'Based on a Novel'),
    (9714,   'Spy'),
    (10683,  'Vampire'),
    (6152,   'Serial Killer'),
    (10349,  'Survival'),
    (5565,   'Biography'),
    (1956,   'Dystopia'),
    (9937,   'Supernatural'),
    (3388,   'Wedding'),
    (9673,   'Based on Comic'),
    (2343,   'Haunting'),
    (6054,   'Friendship'),
    (161155, 'Coming of Age'),
    (9799,   'Romantic Comedy'),
    (1701,   'Hero'),
    (1299,   'Monster'),
    (12565,  'Post-Apocalyptic Future'),
    (14544,  'Robot'),
    (1852,   'Dinosaur'),
]


# ---------------------------------------------------------------------------
# TV COLLECTIONS / UNIVERSES
# ---------------------------------------------------------------------------
# Each entry: universe name + list of TMDB tv show IDs (verified)
TV_COLLECTIONS = [
    ('Star Trek Universe', [
        253, 655, 580, 1855, 314, 67198, 85949, 85948, 106393, 85950,
    ]),
    ('Star Wars (TV)', [
        4194, 60554, 82856, 115036, 92830, 83867, 114478, 203085, 202555,
    ]),
    ('Marvel (Disney+ & Netflix)', [
        88329, 88396, 84958, 91363, 88321, 92749, 92782, 95557,
        61889, 62126, 62127, 62285,
    ]),
    ('DC Arrowverse', [
        1412, 60735, 62688, 60574, 66190, 60708, 62643, 79501, 110492,
    ]),
    ('Law & Order Universe', [
        1119, 1468, 1469, 5255, 28374, 122266,
    ]),
    ('CSI Universe', [
        1431, 1620, 1615, 4478, 88336,
    ]),
    ('NCIS Universe', [
        4614, 17610, 74536, 132285, 202881,
    ]),
    ('Chicago Universe (One Chicago)', [
        1955, 63351, 60572, 68716,
    ]),
    ('FBI Universe (Dick Wolf)', [
        81356, 95396, 127532,
    ]),
    ('Doctor Who Universe', [
        57243, 121, 4629, 11557, 121770,
    ]),
    ('Walking Dead Universe', [
        1402, 62286, 77871, 155770, 205715, 205589, 205588,
    ]),
    ('Yellowstone / Dutton Universe', [
        73586, 106449, 136017,
    ]),
    ('Breaking Bad Universe', [
        1396, 60059,
    ]),
    ('Game of Thrones Universe', [
        1399, 94997, 100088,
    ]),
    ('The Office (US + UK)', [
        2316, 2996,
    ]),
    ('9-1-1 Universe', [
        79744, 82867,
    ]),
    ('Grey\'s Anatomy Universe', [
        1416, 62917, 4572,
    ]),
    ('Criminal Minds Universe', [
        4057, 44288, 60797,
    ]),
    ('CSI: Spinoffs & Cousins', [
        1431, 1620, 1615, 88336,
    ]),
    ('Supernatural Universe', [
        1622, 111003,
    ]),
    ('Power Universe (Starz)', [
        34913, 129257, 129259, 129258,
    ]),
    ('Vampire Diaries Universe', [
        1220, 46786, 88330,
    ]),
]
