"""File generated by TLObjects' generator. All changes will be ERASED"""
from ...tl.tlobject import TLObject
from typing import Optional, List, Union, TYPE_CHECKING
import os
import struct
from datetime import datetime
if TYPE_CHECKING:
    from ...tl.types import TypeChat, TypeCommunityPeerRequest, TypeUser



class ParticipantJoinedChats(TLObject):
    CONSTRUCTOR_ID = 0x8d78512a
    SUBCLASS_OF_ID = 0x86dab595

    def __init__(self, creator_chat_ids: List[int], joined_chat_ids: List[int], chats: List['TypeChat'], users: List['TypeUser']):
        """
        Constructor for communities.ParticipantJoinedChats: Instance of ParticipantJoinedChats.
        """
        self.creator_chat_ids = creator_chat_ids
        self.joined_chat_ids = joined_chat_ids
        self.chats = chats
        self.users = users

    def to_dict(self):
        return {
            '_': 'ParticipantJoinedChats',
            'creator_chat_ids': [] if self.creator_chat_ids is None else self.creator_chat_ids[:],
            'joined_chat_ids': [] if self.joined_chat_ids is None else self.joined_chat_ids[:],
            'chats': [] if self.chats is None else [x.to_dict() if isinstance(x, TLObject) else x for x in self.chats],
            'users': [] if self.users is None else [x.to_dict() if isinstance(x, TLObject) else x for x in self.users]
        }

    def _bytes(self):
        return b''.join((
            b'*Qx\x8d',
            b'\x15\xc4\xb5\x1c',struct.pack('<i', len(self.creator_chat_ids)),b''.join(struct.pack('<q', x) for x in self.creator_chat_ids),
            b'\x15\xc4\xb5\x1c',struct.pack('<i', len(self.joined_chat_ids)),b''.join(struct.pack('<q', x) for x in self.joined_chat_ids),
            b'\x15\xc4\xb5\x1c',struct.pack('<i', len(self.chats)),b''.join(x._bytes() for x in self.chats),
            b'\x15\xc4\xb5\x1c',struct.pack('<i', len(self.users)),b''.join(x._bytes() for x in self.users),
        ))

    @classmethod
    def from_reader(cls, reader):
        reader.read_int()
        _creator_chat_ids = []
        for _ in range(reader.read_int()):
            _x = reader.read_long()
            _creator_chat_ids.append(_x)

        reader.read_int()
        _joined_chat_ids = []
        for _ in range(reader.read_int()):
            _x = reader.read_long()
            _joined_chat_ids.append(_x)

        reader.read_int()
        _chats = []
        for _ in range(reader.read_int()):
            _x = reader.tgread_object()
            _chats.append(_x)

        reader.read_int()
        _users = []
        for _ in range(reader.read_int()):
            _x = reader.tgread_object()
            _users.append(_x)

        return cls(creator_chat_ids=_creator_chat_ids, joined_chat_ids=_joined_chat_ids, chats=_chats, users=_users)


class PeerLinkRequests(TLObject):
    CONSTRUCTOR_ID = 0x2244afad
    SUBCLASS_OF_ID = 0x43aa06ef

    def __init__(self, total_count: int, requests: List['TypeCommunityPeerRequest'], chats: List['TypeChat'], users: List['TypeUser'], next_offset: Optional[str]=None):
        """
        Constructor for communities.PeerLinkRequests: Instance of PeerLinkRequests.
        """
        self.total_count = total_count
        self.requests = requests
        self.chats = chats
        self.users = users
        self.next_offset = next_offset

    def to_dict(self):
        return {
            '_': 'PeerLinkRequests',
            'total_count': self.total_count,
            'requests': [] if self.requests is None else [x.to_dict() if isinstance(x, TLObject) else x for x in self.requests],
            'chats': [] if self.chats is None else [x.to_dict() if isinstance(x, TLObject) else x for x in self.chats],
            'users': [] if self.users is None else [x.to_dict() if isinstance(x, TLObject) else x for x in self.users],
            'next_offset': self.next_offset
        }

    def _bytes(self):
        return b''.join((
            b'\xad\xafD"',
            struct.pack('<I', (0 if self.next_offset is None or self.next_offset is False else 1)),
            struct.pack('<i', self.total_count),
            b'\x15\xc4\xb5\x1c',struct.pack('<i', len(self.requests)),b''.join(x._bytes() for x in self.requests),
            b'' if self.next_offset is None or self.next_offset is False else (self.serialize_bytes(self.next_offset)),
            b'\x15\xc4\xb5\x1c',struct.pack('<i', len(self.chats)),b''.join(x._bytes() for x in self.chats),
            b'\x15\xc4\xb5\x1c',struct.pack('<i', len(self.users)),b''.join(x._bytes() for x in self.users),
        ))

    @classmethod
    def from_reader(cls, reader):
        flags = reader.read_int()

        _total_count = reader.read_int()
        reader.read_int()
        _requests = []
        for _ in range(reader.read_int()):
            _x = reader.tgread_object()
            _requests.append(_x)

        if flags & 1:
            _next_offset = reader.tgread_string()
        else:
            _next_offset = None
        reader.read_int()
        _chats = []
        for _ in range(reader.read_int()):
            _x = reader.tgread_object()
            _chats.append(_x)

        reader.read_int()
        _users = []
        for _ in range(reader.read_int()):
            _x = reader.tgread_object()
            _users.append(_x)

        return cls(total_count=_total_count, requests=_requests, chats=_chats, users=_users, next_offset=_next_offset)

