"""File generated by TLObjects' generator. All changes will be ERASED"""
from ...tl.tlobject import TLObject
from typing import Optional, List, Union, TYPE_CHECKING
import os
import struct
from datetime import datetime
if TYPE_CHECKING:
    from ...tl.types import TypeEphemeralMessage



class WelcomeMessages(TLObject):
    CONSTRUCTOR_ID = 0x104fc872
    SUBCLASS_OF_ID = 0x6f749a2d

    def __init__(self, hash: int, messages: List['TypeEphemeralMessage']):
        """
        Constructor for ephemeral.WelcomeMessages: Instance of either WelcomeMessagesNotModified, WelcomeMessages.
        """
        self.hash = hash
        self.messages = messages

    def to_dict(self):
        return {
            '_': 'WelcomeMessages',
            'hash': self.hash,
            'messages': [] if self.messages is None else [x.to_dict() if isinstance(x, TLObject) else x for x in self.messages]
        }

    def _bytes(self):
        return b''.join((
            b'r\xc8O\x10',
            struct.pack('<q', self.hash),
            b'\x15\xc4\xb5\x1c',struct.pack('<i', len(self.messages)),b''.join(x._bytes() for x in self.messages),
        ))

    @classmethod
    def from_reader(cls, reader):
        _hash = reader.read_long()
        reader.read_int()
        _messages = []
        for _ in range(reader.read_int()):
            _x = reader.tgread_object()
            _messages.append(_x)

        return cls(hash=_hash, messages=_messages)


class WelcomeMessagesNotModified(TLObject):
    CONSTRUCTOR_ID = 0x59ffdb31
    SUBCLASS_OF_ID = 0x6f749a2d

    def to_dict(self):
        return {
            '_': 'WelcomeMessagesNotModified'
        }

    def _bytes(self):
        return b''.join((
            b'1\xdb\xffY',
        ))

    @classmethod
    def from_reader(cls, reader):
        return cls()

