# -*- coding: utf-8 -*-
"""
	luc_kodi Add-on
	Gemini API client for AI-powered natural language search.

	v2 changes (debug version):
	- No module-level requests.Session / urllib3.Retry (some Android Kodi builds
	  fail silently on module import otherwise).
	- Manual cache via cache.cache_get/cache_insert (bypasses cache.get()'s
	  bare except that swallowed exceptions).
	- Diagnostic logging via xbmc.log(LOGERROR) which always shows regardless
	  of luc_kodi's debug.enabled setting. Search log for "[luc_kodi-gemini]".
	- Exposes last_error_message() so ai_search can display the real failure
	  reason to the user.
"""

import json
import hashlib
import xbmc
from resources.lib.database import cache
from resources.lib.modules.control import setting as getSetting

base_url = 'https://generativelanguage.googleapis.com/v1beta'
# Default lead: gemini-3.1-flash-lite (GA since 2026-05-07). For our use case —
# short prompt-to-intent translation, structured output, no agentic/tool use —
# 3.1 Flash-Lite outperforms 2.5 Flash on speed (2.5x faster TTFT, +45% output
# speed) at similar free-tier quota, while 3.5 Flash (also GA from I/O 2026-05-19)
# is optimized for long-horizon agentic tasks and is overkill here.
default_model = 'gemini-3.1-flash-lite'
# Fallback chain used when the primary model fails on all keys with a
# model-generic error (429 quota, 404 model-not-found, 503 unavailable).
# Different models have independent daily quotas and independent rollouts,
# so cycling through them effectively multiplies available free requests
# AND survives regional rollout gaps (e.g. a brand-new GA model not yet
# enabled for one of the user's Cloud projects).
# All models below are AI Studio FREE-TIER compatible (no paid plan required);
# tier 1+ users get higher RPM/RPD on each but the chain still works as-is.
# Order: best quality/cost for our task → premium fallback → legacy stable fallbacks.
# REMOVED 2026-05-21:
#   - gemini-2.0-flash         (shutdown 2026-06-01)
#   - gemini-3-flash-preview   (superseded by gemini-3.5-flash GA)
#   - "-preview" suffix on 3.1 Flash-Lite (GA stable since 2026-05-07)
fallback_models = (
	'gemini-3.1-flash-lite',       # GA 2026-05-07 — best speed/quality at lowest cost for this task
	'gemini-3.5-flash',            # GA 2026-05-19 — premium fallback (free tier with quotas; agentic-grade)
	'gemini-2.5-flash-lite',       # stable workhorse — highest free RPD on Tier 1+ (1500 RPD)
	'gemini-2.5-flash',            # stable fallback
	'gemini-2.5-pro',              # last resort — strictest free quota (5 RPM / 50 RPD) but max quality
)
timeout = 25
empty_setting_check = (None, '', 'empty_setting')
cache_prefix = 'gemini_intent::'
cache_ttl_hours = 168  # 1 week per unique prompt
# Bump this whenever prompt_template changes materially so old cache entries
# (generated by the previous prompt) are treated as stale.
#   v2 — few-shot examples
#   v3 — 2026-05-21: model chain migration (3.1 Flash-Lite leads, drop 2.0 Flash);
#        invalidate to avoid mixing responses from heterogeneous model versions.
cache_version = 'v3'
log_tag = '[luc_kodi-gemini]'

# Last diagnostic message (for UI). Cleared on success.
_last_error = ''

response_schema = {
	'type': 'object',
	'properties': {
		'media_type': {
			'type': 'string',
			'enum': ['movie', 'tvshow']
		},
		'genres': {
			'type': 'array',
			'items': {'type': 'string'}
		},
		'keywords': {
			'type': 'array',
			'items': {'type': 'string'}
		},
		'people': {
			'type': 'array',
			'items': {'type': 'string'}
		},
		'tone_descriptors': {
			'type': 'array',
			'items': {'type': 'string'}
		},
		'example_titles': {
			'type': 'array',
			'items': {'type': 'string'}
		},
		'year_range': {
			'type': 'object',
			'properties': {
				'start': {'type': ['integer', 'null']},
				'end': {'type': ['integer', 'null']}
			},
			'required': ['start', 'end']
		},
		'spanish_language_preferred': {
			'type': 'boolean'
		},
		'exclude_terms': {
			'type': 'array',
			'items': {'type': 'string'}
		}
	},
	'required': ['media_type', 'genres', 'keywords', 'people', 'tone_descriptors', 'example_titles', 'year_range', 'spanish_language_preferred', 'exclude_terms']
}

prompt_template = '''Interpret this natural-language movie or TV discovery request for a Kodi addon.
The user may write in Spanish or English. Return ONLY JSON matching the provided schema.

Rules:
- Choose exactly one media_type: "movie" or "tvshow".
- The request is always about movies or TV shows.
- If the request is short or title-like, prefer direct title/franchise matches in example_titles.
- genres MUST be short canonical English labels (e.g. action, comedy, drama, sci-fi, thriller, romance, horror, documentary, animation, family) even if the user writes in Spanish.
- Be CONSERVATIVE with genres. Only include a genre if it is clearly implied by the request. When the request is thematic (e.g. "movies with sharks", "time travel movies", "films set in Rome"), prefer putting the theme in keywords and leaving genres empty or with a single broad genre.
- If the request mentions a specific actor, performer, director or creator, put that person in "people".
- Do not treat a named person as just a loose keyword when they are clearly intended as cast or creator guidance.
- keywords should be short specific English thematic terms (single words when possible), not full phrases.
- tone_descriptors should be short mood descriptors in English.
- example_titles should contain at most 3 titles using canonical titles when possible.
- Use null for unknown year_range values.
- Set spanish_language_preferred=true ONLY when the user explicitly asks for Spanish-language productions, mentions Spain or Latin America, or a Spanish/Latin American director. A prompt simply written in Spanish does NOT by itself imply this.
- Do not explain your reasoning.

Examples (for guidance, do NOT copy literally):

Request: "Movies with sharks"
→ { "media_type": "movie", "genres": [], "keywords": ["shark"], "people": [], "tone_descriptors": [], "example_titles": ["Jaws", "The Meg", "47 Meters Down"], "year_range": {"start": null, "end": null}, "spanish_language_preferred": false, "exclude_terms": [] }

Request: "romantic comedy"
→ { "media_type": "movie", "genres": ["comedy", "romance"], "keywords": [], "people": [], "tone_descriptors": ["lighthearted"], "example_titles": [], "year_range": {"start": null, "end": null}, "spanish_language_preferred": false, "exclude_terms": [] }

Request: "Tom Cruise action movies from the 90s"
→ { "media_type": "movie", "genres": ["action"], "keywords": [], "people": ["Tom Cruise"], "tone_descriptors": [], "example_titles": ["Mission: Impossible", "Top Gun"], "year_range": {"start": 1990, "end": 1999}, "spanish_language_preferred": false, "exclude_terms": [] }

Request: "peliculas espanolas de humor negro"
→ { "media_type": "movie", "genres": ["comedy"], "keywords": ["dark humor", "black comedy"], "people": [], "tone_descriptors": ["dark"], "example_titles": ["El dia de la bestia", "Comunidad"], "year_range": {"start": null, "end": null}, "spanish_language_preferred": true, "exclude_terms": [] }

Request: "time travel thrillers"
→ { "media_type": "movie", "genres": ["thriller"], "keywords": ["time travel"], "people": [], "tone_descriptors": ["mind-bending"], "example_titles": ["Primer", "Looper", "Predestination"], "year_range": {"start": null, "end": null}, "spanish_language_preferred": false, "exclude_terms": [] }

User request: %s'''

media_type_aliases = {
	'movie': 'movie', 'film': 'movie', 'pelicula': 'movie', 'peliculas': 'movie',
	'tv': 'tvshow', 'tv_show': 'tvshow', 'tvshow': 'tvshow', 'show': 'tvshow',
	'series': 'tvshow', 'serie': 'tvshow', 'television': 'tvshow'
}


# ──────────────────────────────────────────────────────────────────────
# Public API
# ──────────────────────────────────────────────────────────────────────

def last_error_message():
	"""Returns a short human-readable description of the most recent failure."""
	return _last_error


def gemini_api_keys():
	"""Return list of configured Gemini API keys (1-3), filtering empties and dups."""
	keys = []
	for setting_id in ('gemini.api.key', 'gemini.api.key2', 'gemini.api.key3'):
		key = getSetting(setting_id, '')
		if key in empty_setting_check or key in keys: continue
		keys.append(key)
	return keys


def has_gemini_keys():
	return bool(gemini_api_keys())


# Remap legacy / deprecated model strings stored in userdata settings to current
# equivalents. Triggered when an updating user has an older value selected that
# is no longer in the settings dropdown — without this they'd keep hitting a
# dead endpoint until they re-open settings and re-pick.
_legacy_model_map = {
	'gemini-2.0-flash':                'gemini-3.1-flash-lite',  # shutdown 2026-06-01
	'gemini-2.0-flash-lite':           'gemini-3.1-flash-lite',  # shutdown 2026-06-01
	'gemini-3-flash-preview':          'gemini-3.5-flash',       # superseded by 3.5 Flash GA
	'gemini-3.1-flash-lite-preview':   'gemini-3.1-flash-lite',  # GA stable since 2026-05-07
}


def gemini_model():
	model = getSetting('gemini.model', '')
	if not model:
		return default_model
	# Auto-migrate legacy stored selections; users see the new dropdown values
	# from then on (Kodi re-saves the resolved value the next time they open settings).
	return _legacy_model_map.get(model, model)


def interpret_prompt(prompt):
	"""Public entry point. Returns normalized intent dict or None.
	Uses manual cache keyed on prompt+model (168h).
	Automatically falls back through fallback_models chain when all keys
	hit 429 on the primary model (independent daily quotas per model)."""
	global _last_error
	_last_error = ''

	if not prompt:
		_last_error = 'Empty prompt'
		return None
	if not has_gemini_keys():
		_last_error = 'No Gemini API keys configured'
		return None
	prompt = prompt.strip()
	if not prompt:
		_last_error = 'Empty prompt'
		return None

	# Cache is keyed on prompt only (not model) — once we've interpreted a
	# prompt successfully with ANY model, reuse it regardless of which model
	# produced it. Avoids re-hitting Gemini when the user retries the same query.
	cache_key = _make_cache_key(prompt)
	cached = _cache_load(cache_key)
	if cached is not None:
		_log('Cache hit for prompt: %s' % prompt[:60])
		return cached

	# Build the model chain: primary (from settings) first, then fallbacks,
	# deduplicated preserving order.
	primary = gemini_model()
	model_chain = [primary] + [m for m in fallback_models if m != primary]

	last_err = 'Unknown error'
	for model in model_chain:
		_log('Calling Gemini for prompt: %s (model=%s)' % (prompt[:60], model))
		raw = _call_gemini(prompt, model)
		if raw:
			normalized = _normalize(raw)
			if normalized and normalized.get('media_type') in ('movie', 'tvshow'):
				_cache_save(cache_key, normalized)
				_log('Gemini success (model=%s). Intent: media_type=%s genres=%s people=%s' % (
					model,
					normalized.get('media_type'),
					normalized.get('genres'),
					normalized.get('people'),
				))
				return normalized
			_log('Gemini returned unusable payload, trying next model', level=xbmc.LOGWARNING)
			last_err = 'Gemini returned unusable payload'
			continue
		# _last_error was set by _call_gemini — capture and decide
		last_err = _last_error or last_err
		# Try the next model when the failure is generic-to-this-model and another
		# model in the chain may succeed:
		#   - 429 / RESOURCE_EXHAUSTED → quota exhausted on every key for this model
		#     (other models have independent quota buckets)
		#   - 404 / NOT_FOUND          → model not available to ANY of our projects yet
		#     (likely a rollout still in progress — fall back to a stable model)
		#   - 503 / UNAVAILABLE        → this model overloaded across all keys
		#     (sibling models may still be serving)
		# Anything else (auth, schema, network, malformed prompt) won't be fixed
		# by switching model — abort the chain and surface the friendly error.
		retriable = (
			'HTTP 429' in last_err or 'RESOURCE_EXHAUSTED' in last_err or
			'HTTP 404' in last_err or 'NOT_FOUND'          in last_err or
			'HTTP 503' in last_err or 'UNAVAILABLE'        in last_err
		)
		if not retriable:
			_log('Non-retriable error — aborting model chain: %s' % last_err, level=xbmc.LOGERROR)
			break
		_log('Model %s exhausted on all keys (%s). Silently trying next model in chain.' % (
			model, last_err.split(':')[0]), level=xbmc.LOGWARNING)

	_last_error = _friendly_error(last_err)
	return None


def _friendly_error(raw):
	"""Humanize known technical errors."""
	if not raw: return 'Unknown error'
	if 'HTTP 429' in raw or 'RESOURCE_EXHAUSTED' in raw:
		return 'Cuota diaria Gemini agotada. Reintenta manana o anade una Gemini API key de un proyecto distinto.'
	if 'HTTP 503' in raw or 'UNAVAILABLE' in raw:
		return 'Gemini sobrecargado. Reintenta en 1-2 minutos.'
	if 'HTTP 403' in raw or 'PERMISSION_DENIED' in raw:
		return 'Gemini API key invalida o revocada.'
	if 'HTTP 400' in raw:
		return 'Peticion a Gemini rechazada: ' + raw[:80]
	return raw[:120]


# ──────────────────────────────────────────────────────────────────────
# HTTP call (no session, no retry adapter — one request per key, in-loop)
# ──────────────────────────────────────────────────────────────────────

def _call_gemini(prompt, model):
	global _last_error
	try:
		import requests
	except Exception as e:
		_last_error = 'requests import failed: %s' % e
		_log(_last_error, level=xbmc.LOGERROR)
		return None

	api_keys = gemini_api_keys()
	url = '%s/models/%s:generateContent' % (base_url, model)

	try:
		payload_text = prompt_template % prompt
	except Exception as e:
		_last_error = 'Prompt formatting failed: %s' % e
		_log(_last_error, level=xbmc.LOGERROR)
		return None

	payload = {
		'contents': [{'parts': [{'text': payload_text}]}],
		'generationConfig': {
			'temperature': 0.2,
			'responseMimeType': 'application/json',
			'responseJsonSchema': response_schema
		}
	}

	try:
		body = json.dumps(payload)
	except Exception as e:
		_last_error = 'JSON serialization failed: %s' % e
		_log(_last_error, level=xbmc.LOGERROR)
		return None

	last_err = 'Unknown error'
	for idx, api_key in enumerate(api_keys, start=1):
		headers = {'x-goog-api-key': api_key, 'Content-Type': 'application/json'}
		try:
			_log('POST attempt %d to %s' % (idx, url))
			response = requests.post(url, headers=headers, data=body, timeout=timeout)
		except requests.exceptions.SSLError as e:
			last_err = 'SSL error: %s' % e
			_log(last_err, level=xbmc.LOGERROR)
			continue
		except requests.exceptions.ConnectionError as e:
			last_err = 'Connection error: %s' % e
			_log(last_err, level=xbmc.LOGERROR)
			continue
		except requests.exceptions.Timeout as e:
			last_err = 'Timeout: %s' % e
			_log(last_err, level=xbmc.LOGERROR)
			continue
		except Exception as e:
			last_err = '%s: %s' % (type(e).__name__, e)
			_log('Unexpected request failure: %s' % last_err, level=xbmc.LOGERROR)
			continue

		if response.status_code == 200:
			try:
				data = response.json()
			except Exception as e:
				last_err = 'JSON decode failed: %s' % e
				_log(last_err, level=xbmc.LOGERROR)
				continue
			parsed = _parse_response(data)
			if parsed:
				return parsed
			last_err = 'Unparseable Gemini 200 response'
			try: body_snip = response.text[:300]
			except Exception: body_snip = ''
			_log('%s. Raw snippet: %s' % (last_err, body_snip), level=xbmc.LOGWARNING)
			continue

		# Non-200 — decide if we rotate to next key or stop
		err = _error_details(response)
		last_err = 'HTTP %d (%s): %s' % (err['status_code'], err['status'], err['message'])
		_log('Gemini error (key #%d): %s' % (idx, last_err), level=xbmc.LOGWARNING)
		if not _should_try_next_key(err):
			break  # Not a quota error — other keys won't help

	_last_error = last_err
	return None


def _error_details(response):
	status = ''
	message = ''
	try:
		data = response.json()
		err = data.get('error') or {}
		status = err.get('status') or ''
		message = err.get('message') or ''
	except Exception:
		try: message = response.text[:200]
		except Exception: message = ''
	return {'status_code': response.status_code, 'status': status, 'message': message}


def _should_try_next_key(error_details):
	"""Return True when the error is project-specific and another key (from a
	different Google Cloud project) might succeed for the same model.

	Retriable across keys:
	  - 429 / RESOURCE_EXHAUSTED   → daily/per-minute quota exhausted on this project
	  - 404 / NOT_FOUND            → model not exposed to this project (region rollout)
	  - 503 / UNAVAILABLE          → model serving capacity issue, may not affect every project
	"""
	if not error_details: return False
	status_code = error_details.get('status_code')
	status = error_details.get('status') or ''
	if status_code == 429 or status == 'RESOURCE_EXHAUSTED': return True
	if status_code == 404 or status == 'NOT_FOUND': return True
	if status_code == 503 or status == 'UNAVAILABLE': return True
	return False


def _parse_response(response):
	try:
		text = _extract_text(response)
		if not text: return None
		try:
			return json.loads(text)
		except Exception:
			text = text.replace('```json', '').replace('```', '').strip()
			return json.loads(text)
	except Exception:
		return None


def _extract_text(response):
	try:
		candidates = response.get('candidates') or []
		for candidate in candidates:
			content = candidate.get('content') or {}
			for part in content.get('parts', []):
				text = part.get('text')
				if text: return text
	except Exception:
		pass
	return None


# ──────────────────────────────────────────────────────────────────────
# Manual cache (bypasses cache.get()'s silent except)
# ──────────────────────────────────────────────────────────────────────

def _make_cache_key(prompt):
	"""Cache key is per-prompt (not per-model) because an intent is an intent —
	once we've translated the prompt successfully, reuse it regardless of which
	model produced it. cache_version invalidates stale entries across prompt changes."""
	blob = ('%s||%s' % (cache_version, prompt)).encode('utf-8')
	return cache_prefix + hashlib.md5(blob).hexdigest()


def _cache_load(cache_key):
	"""Return cached dict or None. On any error returns None."""
	try:
		row = cache.cache_get(cache_key)
		if not row: return None
		from time import time as _time
		if (_time() - int(row['date'])) > (cache_ttl_hours * 3600):
			return None
		raw = row.get('value')
		if not raw: return None
		return json.loads(raw)
	except Exception as e:
		_log('Cache load failed (ignored): %s' % e, level=xbmc.LOGDEBUG)
		return None


def _cache_save(cache_key, payload):
	try:
		cache.cache_insert(cache_key, json.dumps(payload))
	except Exception as e:
		_log('Cache save failed (ignored): %s' % e, level=xbmc.LOGDEBUG)


# ──────────────────────────────────────────────────────────────────────
# Helpers
# ──────────────────────────────────────────────────────────────────────

def _normalize(data):
	def clean_list(value, limit):
		if not isinstance(value, list): return []
		results = []
		for item in value:
			try: item = str(item).strip()
			except Exception: continue
			if not item or item in results: continue
			results.append(item)
			if len(results) == limit: break
		return results
	def int_or_none(value):
		try: return int(value)
		except Exception: return None
	media_type = media_type_aliases.get(str(data.get('media_type', '')).strip().lower(), 'movie')
	year_range = data.get('year_range') or {}
	start_year = int_or_none(year_range.get('start'))
	end_year = int_or_none(year_range.get('end'))
	if all((start_year, end_year)) and start_year > end_year:
		start_year, end_year = end_year, start_year
	return {
		'media_type': media_type,
		'genres': clean_list(data.get('genres'), 5),
		'keywords': clean_list(data.get('keywords'), 5),
		'people': clean_list(data.get('people'), 4),
		'tone_descriptors': clean_list(data.get('tone_descriptors'), 5),
		'example_titles': clean_list(data.get('example_titles'), 3),
		'year_range': {'start': start_year, 'end': end_year},
		'spanish_language_preferred': bool(data.get('spanish_language_preferred', False)),
		'exclude_terms': clean_list(data.get('exclude_terms'), 5)
	}


def _log(message, level=xbmc.LOGINFO):
	"""Unconditional xbmc.log — visible regardless of luc_kodi's debug.enabled."""
	try:
		xbmc.log('%s %s' % (log_tag, message), level)
	except Exception:
		pass
