"""File generated by TLObjects' generator. All changes will be ERASED"""
from ...tl.tlobject import TLObject
from ...tl.tlobject import TLRequest
from typing import Optional, List, Union, TYPE_CHECKING
import os
import struct
from datetime import datetime
if TYPE_CHECKING:
    from ...tl.types import TypeInputChannel, TypeInputPeer



class CreateRequest(TLRequest):
    CONSTRUCTOR_ID = 0xa63859ec
    SUBCLASS_OF_ID = 0x8af52aac

    def __init__(self, title: str, peer: 'TypeInputPeer', hidden: Optional[bool]=None, about: Optional[str]=None):
        """
        :returns Updates: Instance of either UpdatesTooLong, UpdateShortMessage, UpdateShortChatMessage, UpdateShort, UpdatesCombined, Updates, UpdateShortSentMessage.
        """
        self.title = title
        self.peer = peer
        self.hidden = hidden
        self.about = about

    async def resolve(self, client, utils):
        self.peer = utils.get_input_peer(await client.get_input_entity(self.peer))

    def to_dict(self):
        return {
            '_': 'CreateRequest',
            'title': self.title,
            'peer': self.peer.to_dict() if isinstance(self.peer, TLObject) else self.peer,
            'hidden': self.hidden,
            'about': self.about
        }

    def _bytes(self):
        return b''.join((
            b'\xecY8\xa6',
            struct.pack('<I', (0 if self.hidden is None or self.hidden is False else 2) | (0 if self.about is None or self.about is False else 1)),
            self.serialize_bytes(self.title),
            b'' if self.about is None or self.about is False else (self.serialize_bytes(self.about)),
            self.peer._bytes(),
        ))

    @classmethod
    def from_reader(cls, reader):
        flags = reader.read_int()

        _hidden = bool(flags & 2)
        _title = reader.tgread_string()
        if flags & 1:
            _about = reader.tgread_string()
        else:
            _about = None
        _peer = reader.tgread_object()
        return cls(title=_title, peer=_peer, hidden=_hidden, about=_about)


class GetJoinedCommunitiesRequest(TLRequest):
    CONSTRUCTOR_ID = 0xa663e830
    SUBCLASS_OF_ID = 0x99d5cb14

    def to_dict(self):
        return {
            '_': 'GetJoinedCommunitiesRequest'
        }

    def _bytes(self):
        return b''.join((
            b'0\xe8c\xa6',
        ))

    @classmethod
    def from_reader(cls, reader):
        return cls()


class GetParticipantJoinedChatsRequest(TLRequest):
    CONSTRUCTOR_ID = 0xf87eabab
    SUBCLASS_OF_ID = 0x86dab595

    def __init__(self, community: 'TypeInputChannel', participant: 'TypeInputPeer'):
        """
        :returns communities.ParticipantJoinedChats: Instance of ParticipantJoinedChats.
        """
        self.community = community
        self.participant = participant

    async def resolve(self, client, utils):
        self.community = utils.get_input_channel(await client.get_input_entity(self.community))
        self.participant = utils.get_input_peer(await client.get_input_entity(self.participant))

    def to_dict(self):
        return {
            '_': 'GetParticipantJoinedChatsRequest',
            'community': self.community.to_dict() if isinstance(self.community, TLObject) else self.community,
            'participant': self.participant.to_dict() if isinstance(self.participant, TLObject) else self.participant
        }

    def _bytes(self):
        return b''.join((
            b'\xab\xab~\xf8',
            self.community._bytes(),
            self.participant._bytes(),
        ))

    @classmethod
    def from_reader(cls, reader):
        _community = reader.tgread_object()
        _participant = reader.tgread_object()
        return cls(community=_community, participant=_participant)


class GetPeerLinkRequestsRequest(TLRequest):
    CONSTRUCTOR_ID = 0x93773344
    SUBCLASS_OF_ID = 0x43aa06ef

    def __init__(self, community: 'TypeInputChannel', offset: str, limit: int):
        """
        :returns communities.PeerLinkRequests: Instance of PeerLinkRequests.
        """
        self.community = community
        self.offset = offset
        self.limit = limit

    async def resolve(self, client, utils):
        self.community = utils.get_input_channel(await client.get_input_entity(self.community))

    def to_dict(self):
        return {
            '_': 'GetPeerLinkRequestsRequest',
            'community': self.community.to_dict() if isinstance(self.community, TLObject) else self.community,
            'offset': self.offset,
            'limit': self.limit
        }

    def _bytes(self):
        return b''.join((
            b'D3w\x93',
            self.community._bytes(),
            self.serialize_bytes(self.offset),
            struct.pack('<i', self.limit),
        ))

    @classmethod
    def from_reader(cls, reader):
        _community = reader.tgread_object()
        _offset = reader.tgread_string()
        _limit = reader.read_int()
        return cls(community=_community, offset=_offset, limit=_limit)


class ToggleAllPeerLinkRequestApprovalRequest(TLRequest):
    CONSTRUCTOR_ID = 0xbfe3dd3d
    SUBCLASS_OF_ID = 0xf5b399ac

    def __init__(self, community: 'TypeInputChannel', reject: Optional[bool]=None):
        """
        :returns Bool: This type has no constructors.
        """
        self.community = community
        self.reject = reject

    async def resolve(self, client, utils):
        self.community = utils.get_input_channel(await client.get_input_entity(self.community))

    def to_dict(self):
        return {
            '_': 'ToggleAllPeerLinkRequestApprovalRequest',
            'community': self.community.to_dict() if isinstance(self.community, TLObject) else self.community,
            'reject': self.reject
        }

    def _bytes(self):
        return b''.join((
            b'=\xdd\xe3\xbf',
            struct.pack('<I', (0 if self.reject is None or self.reject is False else 1)),
            self.community._bytes(),
        ))

    @classmethod
    def from_reader(cls, reader):
        flags = reader.read_int()

        _reject = bool(flags & 1)
        _community = reader.tgread_object()
        return cls(community=_community, reject=_reject)


class ToggleCommunityCollapsedInDialogsRequest(TLRequest):
    CONSTRUCTOR_ID = 0xd766e3ea
    SUBCLASS_OF_ID = 0x8af52aac

    def __init__(self, community: 'TypeInputChannel', collapsed: Optional[bool]=None):
        """
        :returns Updates: Instance of either UpdatesTooLong, UpdateShortMessage, UpdateShortChatMessage, UpdateShort, UpdatesCombined, Updates, UpdateShortSentMessage.
        """
        self.community = community
        self.collapsed = collapsed

    async def resolve(self, client, utils):
        self.community = utils.get_input_channel(await client.get_input_entity(self.community))

    def to_dict(self):
        return {
            '_': 'ToggleCommunityCollapsedInDialogsRequest',
            'community': self.community.to_dict() if isinstance(self.community, TLObject) else self.community,
            'collapsed': self.collapsed
        }

    def _bytes(self):
        return b''.join((
            b'\xea\xe3f\xd7',
            struct.pack('<I', (0 if self.collapsed is None or self.collapsed is False else 1)),
            self.community._bytes(),
        ))

    @classmethod
    def from_reader(cls, reader):
        flags = reader.read_int()

        _collapsed = bool(flags & 1)
        _community = reader.tgread_object()
        return cls(community=_community, collapsed=_collapsed)


class ToggleParticipantBannedRequest(TLRequest):
    CONSTRUCTOR_ID = 0x9967ad0f
    SUBCLASS_OF_ID = 0xf5b399ac

    def __init__(self, community: 'TypeInputChannel', participant: 'TypeInputPeer', unban: Optional[bool]=None):
        """
        :returns Bool: This type has no constructors.
        """
        self.community = community
        self.participant = participant
        self.unban = unban

    async def resolve(self, client, utils):
        self.community = utils.get_input_channel(await client.get_input_entity(self.community))
        self.participant = utils.get_input_peer(await client.get_input_entity(self.participant))

    def to_dict(self):
        return {
            '_': 'ToggleParticipantBannedRequest',
            'community': self.community.to_dict() if isinstance(self.community, TLObject) else self.community,
            'participant': self.participant.to_dict() if isinstance(self.participant, TLObject) else self.participant,
            'unban': self.unban
        }

    def _bytes(self):
        return b''.join((
            b'\x0f\xadg\x99',
            struct.pack('<I', (0 if self.unban is None or self.unban is False else 1)),
            self.community._bytes(),
            self.participant._bytes(),
        ))

    @classmethod
    def from_reader(cls, reader):
        flags = reader.read_int()

        _unban = bool(flags & 1)
        _community = reader.tgread_object()
        _participant = reader.tgread_object()
        return cls(community=_community, participant=_participant, unban=_unban)


class TogglePeerLinkRequest(TLRequest):
    CONSTRUCTOR_ID = 0x736dcfea
    SUBCLASS_OF_ID = 0xf5b399ac

    def __init__(self, community: 'TypeInputChannel', peer: 'TypeInputPeer', visible: Optional[bool]=None, hidden: Optional[bool]=None, deleted: Optional[bool]=None):
        """
        :returns Bool: This type has no constructors.
        """
        self.community = community
        self.peer = peer
        self.visible = visible
        self.hidden = hidden
        self.deleted = deleted

    async def resolve(self, client, utils):
        self.community = utils.get_input_channel(await client.get_input_entity(self.community))
        self.peer = utils.get_input_peer(await client.get_input_entity(self.peer))

    def to_dict(self):
        return {
            '_': 'TogglePeerLinkRequest',
            'community': self.community.to_dict() if isinstance(self.community, TLObject) else self.community,
            'peer': self.peer.to_dict() if isinstance(self.peer, TLObject) else self.peer,
            'visible': self.visible,
            'hidden': self.hidden,
            'deleted': self.deleted
        }

    def _bytes(self):
        return b''.join((
            b'\xea\xcfms',
            struct.pack('<I', (0 if self.visible is None or self.visible is False else 1) | (0 if self.hidden is None or self.hidden is False else 2) | (0 if self.deleted is None or self.deleted is False else 4)),
            self.community._bytes(),
            self.peer._bytes(),
        ))

    @classmethod
    def from_reader(cls, reader):
        flags = reader.read_int()

        _visible = bool(flags & 1)
        _hidden = bool(flags & 2)
        _deleted = bool(flags & 4)
        _community = reader.tgread_object()
        _peer = reader.tgread_object()
        return cls(community=_community, peer=_peer, visible=_visible, hidden=_hidden, deleted=_deleted)


class TogglePeerLinkRequestApprovalRequest(TLRequest):
    CONSTRUCTOR_ID = 0x8c8219a8
    SUBCLASS_OF_ID = 0xf5b399ac

    def __init__(self, community: 'TypeInputChannel', peer: 'TypeInputPeer', reject: Optional[bool]=None):
        """
        :returns Bool: This type has no constructors.
        """
        self.community = community
        self.peer = peer
        self.reject = reject

    async def resolve(self, client, utils):
        self.community = utils.get_input_channel(await client.get_input_entity(self.community))
        self.peer = utils.get_input_peer(await client.get_input_entity(self.peer))

    def to_dict(self):
        return {
            '_': 'TogglePeerLinkRequestApprovalRequest',
            'community': self.community.to_dict() if isinstance(self.community, TLObject) else self.community,
            'peer': self.peer.to_dict() if isinstance(self.peer, TLObject) else self.peer,
            'reject': self.reject
        }

    def _bytes(self):
        return b''.join((
            b'\xa8\x19\x82\x8c',
            struct.pack('<I', (0 if self.reject is None or self.reject is False else 1)),
            self.community._bytes(),
            self.peer._bytes(),
        ))

    @classmethod
    def from_reader(cls, reader):
        flags = reader.read_int()

        _reject = bool(flags & 1)
        _community = reader.tgread_object()
        _peer = reader.tgread_object()
        return cls(community=_community, peer=_peer, reject=_reject)

