"""File generated by TLObjects' generator. All changes will be ERASED"""
from ...tl.tlobject import TLObject
from ...tl.tlobject import TLRequest
from typing import Optional, List, Union, TYPE_CHECKING
import os
import struct
from datetime import datetime
if TYPE_CHECKING:
    from ...tl.types import TypeInputMedia, TypeInputPeer, TypeInputReplyTo, TypeInputRichMessage, TypeInputUser, TypeMessageEntity, TypeReplyMarkup



class DeleteAllWelcomeMessagesRequest(TLRequest):
    CONSTRUCTOR_ID = 0x734f9721
    SUBCLASS_OF_ID = 0xf5b399ac

    def __init__(self, peer: 'TypeInputPeer'):
        """
        :returns Bool: This type has no constructors.
        """
        self.peer = peer

    async def resolve(self, client, utils):
        self.peer = utils.get_input_peer(await client.get_input_entity(self.peer))

    def to_dict(self):
        return {
            '_': 'DeleteAllWelcomeMessagesRequest',
            'peer': self.peer.to_dict() if isinstance(self.peer, TLObject) else self.peer
        }

    def _bytes(self):
        return b''.join((
            b'!\x97Os',
            self.peer._bytes(),
        ))

    @classmethod
    def from_reader(cls, reader):
        _peer = reader.tgread_object()
        return cls(peer=_peer)


class DeleteMessageRequest(TLRequest):
    CONSTRUCTOR_ID = 0x92f6e797
    SUBCLASS_OF_ID = 0xf5b399ac

    def __init__(self, receiver_id: 'TypeInputUser', id: int, peer: Optional['TypeInputPeer']=None):
        """
        :returns Bool: This type has no constructors.
        """
        self.receiver_id = receiver_id
        self.id = id
        self.peer = peer

    async def resolve(self, client, utils):
        self.receiver_id = utils.get_input_user(await client.get_input_entity(self.receiver_id))
        if self.peer:
            self.peer = utils.get_input_peer(await client.get_input_entity(self.peer))

    def to_dict(self):
        return {
            '_': 'DeleteMessageRequest',
            'receiver_id': self.receiver_id.to_dict() if isinstance(self.receiver_id, TLObject) else self.receiver_id,
            'id': self.id,
            'peer': self.peer.to_dict() if isinstance(self.peer, TLObject) else self.peer
        }

    def _bytes(self):
        return b''.join((
            b'\x97\xe7\xf6\x92',
            struct.pack('<I', (0 if self.peer is None or self.peer is False else 1)),
            b'' if self.peer is None or self.peer is False else (self.peer._bytes()),
            self.receiver_id._bytes(),
            struct.pack('<i', self.id),
        ))

    @classmethod
    def from_reader(cls, reader):
        flags = reader.read_int()

        if flags & 1:
            _peer = reader.tgread_object()
        else:
            _peer = None
        _receiver_id = reader.tgread_object()
        _id = reader.read_int()
        return cls(receiver_id=_receiver_id, id=_id, peer=_peer)


class DeleteWelcomeMessageRequest(TLRequest):
    CONSTRUCTOR_ID = 0xe882a9e1
    SUBCLASS_OF_ID = 0xf5b399ac

    def __init__(self, peer: 'TypeInputPeer', id: int):
        """
        :returns Bool: This type has no constructors.
        """
        self.peer = peer
        self.id = id

    async def resolve(self, client, utils):
        self.peer = utils.get_input_peer(await client.get_input_entity(self.peer))

    def to_dict(self):
        return {
            '_': 'DeleteWelcomeMessageRequest',
            'peer': self.peer.to_dict() if isinstance(self.peer, TLObject) else self.peer,
            'id': self.id
        }

    def _bytes(self):
        return b''.join((
            b'\xe1\xa9\x82\xe8',
            self.peer._bytes(),
            struct.pack('<i', self.id),
        ))

    @classmethod
    def from_reader(cls, reader):
        _peer = reader.tgread_object()
        _id = reader.read_int()
        return cls(peer=_peer, id=_id)


class EditMessageRequest(TLRequest):
    CONSTRUCTOR_ID = 0xcf9c725b
    SUBCLASS_OF_ID = 0x8af52aac

    def __init__(self, receiver_id: 'TypeInputUser', id: int, invert_media: Optional[bool]=None, welcome: Optional[bool]=None, peer: Optional['TypeInputPeer']=None, message: Optional[str]=None, media: Optional['TypeInputMedia']=None, entities: Optional[List['TypeMessageEntity']]=None, reply_markup: Optional['TypeReplyMarkup']=None, rich_message: Optional['TypeInputRichMessage']=None):
        """
        :returns Updates: Instance of either UpdatesTooLong, UpdateShortMessage, UpdateShortChatMessage, UpdateShort, UpdatesCombined, Updates, UpdateShortSentMessage.
        """
        self.receiver_id = receiver_id
        self.id = id
        self.invert_media = invert_media
        self.welcome = welcome
        self.peer = peer
        self.message = message
        self.media = media
        self.entities = entities
        self.reply_markup = reply_markup
        self.rich_message = rich_message

    async def resolve(self, client, utils):
        self.receiver_id = utils.get_input_user(await client.get_input_entity(self.receiver_id))
        if self.peer:
            self.peer = utils.get_input_peer(await client.get_input_entity(self.peer))

        if self.media:
            self.media = utils.get_input_media(self.media)

    def to_dict(self):
        return {
            '_': 'EditMessageRequest',
            'receiver_id': self.receiver_id.to_dict() if isinstance(self.receiver_id, TLObject) else self.receiver_id,
            'id': self.id,
            'invert_media': self.invert_media,
            'welcome': self.welcome,
            'peer': self.peer.to_dict() if isinstance(self.peer, TLObject) else self.peer,
            'message': self.message,
            'media': self.media.to_dict() if isinstance(self.media, TLObject) else self.media,
            'entities': [] if self.entities is None else [x.to_dict() if isinstance(x, TLObject) else x for x in self.entities],
            'reply_markup': self.reply_markup.to_dict() if isinstance(self.reply_markup, TLObject) else self.reply_markup,
            'rich_message': self.rich_message.to_dict() if isinstance(self.rich_message, TLObject) else self.rich_message
        }

    def _bytes(self):
        return b''.join((
            b'[r\x9c\xcf',
            struct.pack('<I', (0 if self.invert_media is None or self.invert_media is False else 32) | (0 if self.welcome is None or self.welcome is False else 64) | (0 if self.peer is None or self.peer is False else 128) | (0 if self.message is None or self.message is False else 1) | (0 if self.media is None or self.media is False else 8) | (0 if self.entities is None or self.entities is False else 2) | (0 if self.reply_markup is None or self.reply_markup is False else 4) | (0 if self.rich_message is None or self.rich_message is False else 16)),
            b'' if self.peer is None or self.peer is False else (self.peer._bytes()),
            self.receiver_id._bytes(),
            struct.pack('<i', self.id),
            b'' if self.message is None or self.message is False else (self.serialize_bytes(self.message)),
            b'' if self.media is None or self.media is False else (self.media._bytes()),
            b'' if self.entities is None or self.entities is False else b''.join((b'\x15\xc4\xb5\x1c',struct.pack('<i', len(self.entities)),b''.join(x._bytes() for x in self.entities))),
            b'' if self.reply_markup is None or self.reply_markup is False else (self.reply_markup._bytes()),
            b'' if self.rich_message is None or self.rich_message is False else (self.rich_message._bytes()),
        ))

    @classmethod
    def from_reader(cls, reader):
        flags = reader.read_int()

        _invert_media = bool(flags & 32)
        _welcome = bool(flags & 64)
        if flags & 128:
            _peer = reader.tgread_object()
        else:
            _peer = None
        _receiver_id = reader.tgread_object()
        _id = reader.read_int()
        if flags & 1:
            _message = reader.tgread_string()
        else:
            _message = None
        if flags & 8:
            _media = reader.tgread_object()
        else:
            _media = None
        if flags & 2:
            reader.read_int()
            _entities = []
            for _ in range(reader.read_int()):
                _x = reader.tgread_object()
                _entities.append(_x)

        else:
            _entities = None
        if flags & 4:
            _reply_markup = reader.tgread_object()
        else:
            _reply_markup = None
        if flags & 16:
            _rich_message = reader.tgread_object()
        else:
            _rich_message = None
        return cls(receiver_id=_receiver_id, id=_id, invert_media=_invert_media, welcome=_welcome, peer=_peer, message=_message, media=_media, entities=_entities, reply_markup=_reply_markup, rich_message=_rich_message)


class GetCallbackAnswerRequest(TLRequest):
    CONSTRUCTOR_ID = 0x3fa464c8
    SUBCLASS_OF_ID = 0x6c4dd18c

    def __init__(self, peer: 'TypeInputPeer', id: int, data: Optional[bytes]=None):
        """
        :returns messages.BotCallbackAnswer: Instance of BotCallbackAnswer.
        """
        self.peer = peer
        self.id = id
        self.data = data

    async def resolve(self, client, utils):
        self.peer = utils.get_input_peer(await client.get_input_entity(self.peer))

    def to_dict(self):
        return {
            '_': 'GetCallbackAnswerRequest',
            'peer': self.peer.to_dict() if isinstance(self.peer, TLObject) else self.peer,
            'id': self.id,
            'data': self.data
        }

    def _bytes(self):
        return b''.join((
            b'\xc8d\xa4?',
            struct.pack('<I', (0 if self.data is None or self.data is False else 2)),
            self.peer._bytes(),
            struct.pack('<i', self.id),
            b'' if self.data is None or self.data is False else (self.serialize_bytes(self.data)),
        ))

    @classmethod
    def from_reader(cls, reader):
        flags = reader.read_int()

        _peer = reader.tgread_object()
        _id = reader.read_int()
        if flags & 2:
            _data = reader.tgread_bytes()
        else:
            _data = None
        return cls(peer=_peer, id=_id, data=_data)


class GetWelcomeMessagesRequest(TLRequest):
    CONSTRUCTOR_ID = 0xdb9ac18d
    SUBCLASS_OF_ID = 0x6f749a2d

    def __init__(self, peer: 'TypeInputPeer', hash: int):
        """
        :returns ephemeral.WelcomeMessages: Instance of either WelcomeMessagesNotModified, WelcomeMessages.
        """
        self.peer = peer
        self.hash = hash

    async def resolve(self, client, utils):
        self.peer = utils.get_input_peer(await client.get_input_entity(self.peer))

    def to_dict(self):
        return {
            '_': 'GetWelcomeMessagesRequest',
            'peer': self.peer.to_dict() if isinstance(self.peer, TLObject) else self.peer,
            'hash': self.hash
        }

    def _bytes(self):
        return b''.join((
            b'\x8d\xc1\x9a\xdb',
            self.peer._bytes(),
            struct.pack('<q', self.hash),
        ))

    @classmethod
    def from_reader(cls, reader):
        _peer = reader.tgread_object()
        _hash = reader.read_long()
        return cls(peer=_peer, hash=_hash)


class ReportMessageRequest(TLRequest):
    CONSTRUCTOR_ID = 0x8704f2bf
    SUBCLASS_OF_ID = 0xacd3f438

    def __init__(self, peer: 'TypeInputPeer', id: int, option: bytes, message: str):
        """
        :returns ReportResult: Instance of either ReportResultChooseOption, ReportResultAddComment, ReportResultReported.
        """
        self.peer = peer
        self.id = id
        self.option = option
        self.message = message

    async def resolve(self, client, utils):
        self.peer = utils.get_input_peer(await client.get_input_entity(self.peer))

    def to_dict(self):
        return {
            '_': 'ReportMessageRequest',
            'peer': self.peer.to_dict() if isinstance(self.peer, TLObject) else self.peer,
            'id': self.id,
            'option': self.option,
            'message': self.message
        }

    def _bytes(self):
        return b''.join((
            b'\xbf\xf2\x04\x87',
            self.peer._bytes(),
            struct.pack('<i', self.id),
            self.serialize_bytes(self.option),
            self.serialize_bytes(self.message),
        ))

    @classmethod
    def from_reader(cls, reader):
        _peer = reader.tgread_object()
        _id = reader.read_int()
        _option = reader.tgread_bytes()
        _message = reader.tgread_string()
        return cls(peer=_peer, id=_id, option=_option, message=_message)


class SendMessageRequest(TLRequest):
    CONSTRUCTOR_ID = 0xba8d5f35
    SUBCLASS_OF_ID = 0x8af52aac

    def __init__(self, receiver_id: 'TypeInputUser', message: str, invert_media: Optional[bool]=None, welcome: Optional[bool]=None, anchor: Optional[bool]=None, noforwards: Optional[bool]=None, peer: Optional['TypeInputPeer']=None, query_id: Optional[int]=None, entities: Optional[List['TypeMessageEntity']]=None, media: Optional['TypeInputMedia']=None, reply_markup: Optional['TypeReplyMarkup']=None, rich_message: Optional['TypeInputRichMessage']=None, random_id: int=None, reply_to: Optional['TypeInputReplyTo']=None):
        """
        :returns Updates: Instance of either UpdatesTooLong, UpdateShortMessage, UpdateShortChatMessage, UpdateShort, UpdatesCombined, Updates, UpdateShortSentMessage.
        """
        self.receiver_id = receiver_id
        self.message = message
        self.invert_media = invert_media
        self.welcome = welcome
        self.anchor = anchor
        self.noforwards = noforwards
        self.peer = peer
        self.query_id = query_id
        self.entities = entities
        self.media = media
        self.reply_markup = reply_markup
        self.rich_message = rich_message
        self.random_id = random_id if random_id is not None else int.from_bytes(os.urandom(8), 'big', signed=True)
        self.reply_to = reply_to

    async def resolve(self, client, utils):
        self.receiver_id = utils.get_input_user(await client.get_input_entity(self.receiver_id))
        if self.peer:
            self.peer = utils.get_input_peer(await client.get_input_entity(self.peer))

        if self.media:
            self.media = utils.get_input_media(self.media)

    def to_dict(self):
        return {
            '_': 'SendMessageRequest',
            'receiver_id': self.receiver_id.to_dict() if isinstance(self.receiver_id, TLObject) else self.receiver_id,
            'message': self.message,
            'invert_media': self.invert_media,
            'welcome': self.welcome,
            'anchor': self.anchor,
            'noforwards': self.noforwards,
            'peer': self.peer.to_dict() if isinstance(self.peer, TLObject) else self.peer,
            'query_id': self.query_id,
            'entities': [] if self.entities is None else [x.to_dict() if isinstance(x, TLObject) else x for x in self.entities],
            'media': self.media.to_dict() if isinstance(self.media, TLObject) else self.media,
            'reply_markup': self.reply_markup.to_dict() if isinstance(self.reply_markup, TLObject) else self.reply_markup,
            'rich_message': self.rich_message.to_dict() if isinstance(self.rich_message, TLObject) else self.rich_message,
            'random_id': self.random_id,
            'reply_to': self.reply_to.to_dict() if isinstance(self.reply_to, TLObject) else self.reply_to
        }

    def _bytes(self):
        return b''.join((
            b'5_\x8d\xba',
            struct.pack('<I', (0 if self.invert_media is None or self.invert_media is False else 64) | (0 if self.welcome is None or self.welcome is False else 128) | (0 if self.anchor is None or self.anchor is False else 512) | (0 if self.noforwards is None or self.noforwards is False else 1024) | (0 if self.peer is None or self.peer is False else 256) | (0 if self.query_id is None or self.query_id is False else 1) | (0 if self.entities is None or self.entities is False else 2) | (0 if self.media is None or self.media is False else 4) | (0 if self.reply_markup is None or self.reply_markup is False else 8) | (0 if self.rich_message is None or self.rich_message is False else 16) | (0 if self.reply_to is None or self.reply_to is False else 32)),
            b'' if self.peer is None or self.peer is False else (self.peer._bytes()),
            self.receiver_id._bytes(),
            b'' if self.query_id is None or self.query_id is False else (struct.pack('<q', self.query_id)),
            self.serialize_bytes(self.message),
            b'' if self.entities is None or self.entities is False else b''.join((b'\x15\xc4\xb5\x1c',struct.pack('<i', len(self.entities)),b''.join(x._bytes() for x in self.entities))),
            b'' if self.media is None or self.media is False else (self.media._bytes()),
            b'' if self.reply_markup is None or self.reply_markup is False else (self.reply_markup._bytes()),
            b'' if self.rich_message is None or self.rich_message is False else (self.rich_message._bytes()),
            struct.pack('<q', self.random_id),
            b'' if self.reply_to is None or self.reply_to is False else (self.reply_to._bytes()),
        ))

    @classmethod
    def from_reader(cls, reader):
        flags = reader.read_int()

        _invert_media = bool(flags & 64)
        _welcome = bool(flags & 128)
        _anchor = bool(flags & 512)
        _noforwards = bool(flags & 1024)
        if flags & 256:
            _peer = reader.tgread_object()
        else:
            _peer = None
        _receiver_id = reader.tgread_object()
        if flags & 1:
            _query_id = reader.read_long()
        else:
            _query_id = None
        _message = reader.tgread_string()
        if flags & 2:
            reader.read_int()
            _entities = []
            for _ in range(reader.read_int()):
                _x = reader.tgread_object()
                _entities.append(_x)

        else:
            _entities = None
        if flags & 4:
            _media = reader.tgread_object()
        else:
            _media = None
        if flags & 8:
            _reply_markup = reader.tgread_object()
        else:
            _reply_markup = None
        if flags & 16:
            _rich_message = reader.tgread_object()
        else:
            _rich_message = None
        _random_id = reader.read_long()
        if flags & 32:
            _reply_to = reader.tgread_object()
        else:
            _reply_to = None
        return cls(receiver_id=_receiver_id, message=_message, invert_media=_invert_media, welcome=_welcome, anchor=_anchor, noforwards=_noforwards, peer=_peer, query_id=_query_id, entities=_entities, media=_media, reply_markup=_reply_markup, rich_message=_rich_message, random_id=_random_id, reply_to=_reply_to)

